### ISSUE TITLE
Network type PlayerMedia need to add http headers param

### ISSUE THREAD

**Issue by sun2008mt** [physia/kflutter#8]
AudioSource.uri() of just_audio has headers param, need to wrap it too

**Comment by mohamadlounnas** [comment]
I added support for it but because VLC doesn't have headers (only user agent) it works only for just_audio (web, ios, android, macos)
i will add support for whenever Windows and Linux be supported
u can use it now as just_audio
`
var player = Player.network("https://example.com/sound.mp3",headers:{
   // ...
});
`

**Comment by poka-IT** [comment]
`headers` property should not available on `network` methode on version 0.1.12.
